In [15]:
from random import *
import pandas as pd
import numpy as np
import scipy.stats as stats
import statistics

In [4]:
numbers = []
for i in range(100):
    numbers.append(randint(1,100))

100

In [16]:
station = pd.read_excel('../data/total_data/역별 데이터.xlsx')
station

호선       역사명  환승        역위도         역경도   일평균승차   일평균하차  일평균승하차     순위  \
0     1  다대포해수욕장역 NaN  35.048670  128.964100  4264.0  3497.0  7761.0   69.0   
1     1     다대포항역 NaN  35.057820  128.971300  2900.0  3321.0  6221.0   80.0   
2     1       낫개역 NaN  35.065265  128.979873  4104.0  4223.0  8327.0   64.0   
3     1      신장림역 NaN  35.074433  128.977041  2777.0  2583.0  5360.0   91.0   
4     1       장림역 NaN  35.081090  128.977500  2854.0  2636.0  5490.0   89.0   
..   ..       ...  ..        ...         ...     ...     ...     ...    ...   
109   4       석대역 NaN  35.218112  129.137179   195.0   151.0   346.0  112.0   
110   4      영산대역 NaN  35.225777  129.146149  2419.0  2377.0  4796.0   95.0   
111   4    동부산대학역 NaN  35.232506  129.154024  2223.0  2097.0  4320.0   97.0   
112   4       고촌역 NaN  35.236031  129.160444   569.0   447.0  1016.0  111.0   
113   4       안평역 NaN  35.237363  129.171823  1753.0  1719.0  3472.0  103.0   

     하행 대기시간  상행 대기시간  
0       20.0      0.0  
1       20.0     20.0  
2       20.0     20.0  
3       20.0     20.0  
4       20.0     20.0  
..       ...      ...  
109     20.0     20.0  
110     20.0     20.0  
111     20.0     20.0  
112     20.0     20.0  
113     30.0      0.0  

[114 rows x 11 columns]

In [21]:
type(list(station.columns))

list

In [56]:
station_test = np.array(list(station.일평균승하차))
station_test

array([ 7761.,  6221.,  8327.,  5360.,  5490.,  6578., 11314., 29080.,
       10929.,  7041., 15271.,  6290.,  5277., 10597., 13846., 27992.,
       28802., 16097., 30061., 10253., 12864.,  6248., 25681., 16322.,
       57826., 28422., 20425., 23612., 30035., 22544., 28565., 15692.,
       24357., 24167., 17955., 15857., 11618.,  9178., 12777., 19370.,
       24411., 11300., 18794., 11305., 14292., 28867.,  5878., 24200.,
       16701., 11471., 10166., 24395., 15595.,  7894.,  4593.,  8343.,
        8248., 14622., 38675.,  9512.,  5799.,  9877., 13621.,  9535.,
       10672.,  6107., 33585.,  6581.,  3426.,  7564.,  7021.,  5185.,
       10481.,  9230., 16561.,  7415.,  2527.,  3881.,  2497.,  7659.,
        3418.,  5641., 10188.,    nan,  7826.,  7754.,  6203., 14799.,
        9546.,  8536., 11065., 15355., 10071.,  8016.,  5802., 19223.,
        5530.,  4251.,  1158., 12374.,    nan,  3796.,  5911.,  2934.,
        5398.,  5157.,  4052.,  3061.,  3738.,   346.,  4796.,  4320.,
      

In [76]:
stats.zscore(station_test,nan_policy='omit')

array([-5.00226897e-01, -6.66113539e-01, -4.39258171e-01, -7.58859252e-01,
       -7.44855834e-01, -6.27657999e-01, -1.17502717e-01,  1.79622590e+00,
       -1.58974378e-01, -5.77784288e-01,  3.08739777e-01, -6.58680956e-01,
       -7.67799896e-01, -1.94736952e-01,  1.55240774e-01,  1.67902807e+00,
        1.76628013e+00,  3.97715339e-01,  1.90189785e+00, -2.31792150e-01,
        4.94611104e-02, -6.63205137e-01,  1.43009039e+00,  4.21952024e-01,
        4.89270473e+00,  1.72534706e+00,  8.63921433e-01,  1.20722061e+00,
        1.89909716e+00,  1.09217714e+00,  1.74075082e+00,  3.54089307e-01,
        1.28747096e+00,  1.26700443e+00,  5.97856495e-01,  3.71862875e-01,
       -8.47562633e-02, -3.47589643e-01,  4.00895923e-02,  7.50278312e-01,
        1.29328777e+00, -1.19010778e-01,  6.88232399e-01, -1.18472185e-01,
        2.03283269e-01,  1.77328184e+00, -7.03061018e-01,  1.27055914e+00,
        4.62777372e-01, -1.00590897e-01, -2.41163668e-01,  1.29156427e+00,
        3.43640603e-01, -

In [90]:
station_test = pd.to_numeric(station_test, errors='coerce')
station_test

array([ 7761.,  6221.,  8327.,  5360.,  5490.,  6578., 11314., 29080.,
       10929.,  7041., 15271.,  6290.,  5277., 10597., 13846., 27992.,
       28802., 16097., 30061., 10253., 12864.,  6248., 25681., 16322.,
       57826., 28422., 20425., 23612., 30035., 22544., 28565., 15692.,
       24357., 24167., 17955., 15857., 11618.,  9178., 12777., 19370.,
       24411., 11300., 18794., 11305., 14292., 28867.,  5878., 24200.,
       16701., 11471., 10166., 24395., 15595.,  7894.,  4593.,  8343.,
        8248., 14622., 38675.,  9512.,  5799.,  9877., 13621.,  9535.,
       10672.,  6107., 33585.,  6581.,  3426.,  7564.,  7021.,  5185.,
       10481.,  9230., 16561.,  7415.,  2527.,  3881.,  2497.,  7659.,
        3418.,  5641., 10188.,    nan,  7826.,  7754.,  6203., 14799.,
        9546.,  8536., 11065., 15355., 10071.,  8016.,  5802., 19223.,
        5530.,  4251.,  1158., 12374.,    nan,  3796.,  5911.,  2934.,
        5398.,  5157.,  4052.,  3061.,  3738.,   346.,  4796.,  4320.,
      

In [95]:
station = station.dropna(subset=['일평균승하차'])
station['일평균승하차'] = station['일평균승하차'].astype(int)

In [96]:
# stats.zscore(station_test,nan_policy='omit')
station_z_scores = list(stats.zscore(station['일평균승하차'],nan_policy='omit'))
station_z_scores

[-0.5002268973180429,
 -0.6661135388670568,
 -0.4392581706188599,
 -0.7588592520967327,
 -0.7448558343036341,
 -0.6276579992352399,
 -0.1175027171728181,
 1.7962259021517146,
 -0.15897437756007157,
 -0.5777842881721273,
 0.30873977672942077,
 -0.6586809555768737,
 -0.7677998957646341,
 -0.19473695223167714,
 0.1552407739973787,
 1.6790280670833202,
 1.7662801317941654,
 0.39771533901480094,
 1.9018978471904047,
 -0.23179215008418413,
 0.049461110360280267,
 -0.6632051367100287,
 1.4300903861613912,
 0.4219520236567023,
 4.892704732001034,
 1.7253470643989541,
 0.863921432926575,
 1.207220606054307,
 1.899097163631785,
 1.0921771429540816,
 1.7407508239713625,
 0.35408930665937843,
 1.2874709618686024,
 1.267004428170997,
 0.5978564948577021,
 0.37186287539677276,
 -0.08475626325664913,
 -0.3475896433732685,
 0.04008959229874507,
 0.7502783116056596,
 1.293287766182659,
 -0.1190107775505364,
 0.6882323989223921,
 -0.11847218455849415,
 0.20328326888754766,
 1.7732818406907147,
 -0.70306

In [98]:
len(station_z_scores)

112

In [108]:
station_use_p = list(station['일평균승하차'])

In [110]:
df3 = makeDataFrame(station_use_p,station_z_scores)
df3

숫자  등급
0    7761   3
1    6221   3
2    8327   4
3    5360   3
4    5490   3
..    ...  ..
107   346   2
108  4796   3
109  4320   3
110  1016   2
111  3472   3

[112 rows x 2 columns]

In [111]:
df.등급.unique()

array([5, 9, 2, 3, 8, 7, 6, 1, 4], dtype=int64)

In [5]:
numbers

[44,
 57,
 60,
 47,
 52,
 97,
 42,
 7,
 19,
 95,
 78,
 72,
 66,
 49,
 49,
 82,
 43,
 48,
 100,
 63,
 4,
 3,
 56,
 96,
 88,
 42,
 83,
 33,
 93,
 23,
 5,
 92,
 24,
 99,
 88,
 13,
 69,
 59,
 71,
 82,
 11,
 2,
 47,
 35,
 21,
 40,
 57,
 38,
 87,
 11,
 8,
 35,
 62,
 15,
 33,
 95,
 4,
 97,
 40,
 76,
 69,
 58,
 29,
 21,
 40,
 50,
 17,
 40,
 65,
 53,
 11,
 14,
 67,
 78,
 64,
 40,
 22,
 36,
 20,
 91,
 89,
 30,
 31,
 100,
 5,
 44,
 87,
 34,
 31,
 95,
 2,
 83,
 24,
 70,
 56,
 40,
 71,
 36,
 21,
 90]

In [14]:
total = 0

for number in numbers:
    total += number

total/100

50.31

In [37]:
statistics.mean(numbers)

50.31

In [40]:
data = np.array(numbers)
data

array([ 44,  57,  60,  47,  52,  97,  42,   7,  19,  95,  78,  72,  66,
        49,  49,  82,  43,  48, 100,  63,   4,   3,  56,  96,  88,  42,
        83,  33,  93,  23,   5,  92,  24,  99,  88,  13,  69,  59,  71,
        82,  11,   2,  47,  35,  21,  40,  57,  38,  87,  11,   8,  35,
        62,  15,  33,  95,   4,  97,  40,  76,  69,  58,  29,  21,  40,
        50,  17,  40,  65,  53,  11,  14,  67,  78,  64,  40,  22,  36,
        20,  91,  89,  30,  31, 100,   5,  44,  87,  34,  31,  95,   2,
        83,  24,  70,  56,  40,  71,  36,  21,  90])

In [44]:
z_scores = list(stats.zscore(data))
z_scores

[-0.21711506722449012,
 0.23019014258824688,
 0.33341442177580155,
 -0.11389078803693542,
 0.05814967727565573,
 1.606513865088976,
 -0.28593125334952657,
 -1.4902145105376647,
 -1.0773173937874458,
 1.5376976789639396,
 0.9527600969011297,
 0.7463115385260204,
 0.5398629801509109,
 -0.04507460191189896,
 -0.04507460191189896,
 1.0903924691512026,
 -0.25152316028700833,
 -0.07948269497441719,
 1.7097381442765307,
 0.4366387009633563,
 -1.5934387897252194,
 -1.6278468827877375,
 0.19578204952572864,
 1.572105772026458,
 1.296841027526312,
 -0.28593125334952657,
 1.124800562213721,
 -0.5956040909121907,
 1.4688814928389031,
 -0.939685021537373,
 -1.559030696662701,
 1.434473399776385,
 -0.9052769284748547,
 1.6753300512140126,
 1.296841027526312,
 -1.2837659521625553,
 0.6430872593384657,
 0.29900632871328336,
 0.7119034454635021,
 1.0903924691512026,
 -1.3525821382875918,
 -1.6622549758502558,
 -0.11389078803693542,
 -0.5267879047871542,
 -1.0085012076624094,
 -0.35474743947456305,
 0.2

In [109]:
def makeDataFrame(stat,z_scores):
    grade = []
    for idx in range(len(z_scores)):
        if z_scores[idx]:
            score = int(z_scores[idx]*2+5)
            grade.append([stat[idx],score])

    return pd.DataFrame(grade,columns=['숫자','등급'])

In [47]:
df2.등급.unique()

array([4, 5, 8, 2, 6, 7, 1, 3], dtype=int64)

z점수 * 2 + 5 -> 정수화 -> stanine 점수

In [15]:
avg = total/100

In [18]:
test = numbers[0]/avg*100*0.5
test

43.72888093818326

In [19]:
def getGrade(per):
    if 0 < per < 4:
        return 1
    elif per < 11:
        return 2
    elif per < 23:
        return 3
    elif per < 40:
        return 4
    elif per < 60:
        return 5
    elif per < 77:
        return 6
    elif per < 89:
        return 7
    elif per < 96:
        return 8
    elif 100 > per > 96:
        return 9
    else:
        print('out of grade')

In [20]:
numNgrade = []

for num in numbers:
    per = num/avg*100*0.5
    numNgrade.append([num,getGrade(per)])

In [38]:
numNgrade

list

In [24]:
df = pd.DataFrame(numNgrade,columns=['숫자','등급'])
df

숫자  등급
0   44   5
1   57   5
2   60   5
3   47   5
4   52   5
..  ..  ..
95  40   4
96  71   6
97  36   4
98  21   3
99  90   8

[100 rows x 2 columns]

In [48]:
df2

숫자  등급
0   44   4
1   57   5
2   60   5
3   47   4
4   52   5
..  ..  ..
95  40   4
96  71   6
97  36   4
98  21   2
99  90   7

[100 rows x 2 columns]

In [34]:
df.등급.unique()

array([5, 9, 2, 3, 8, 7, 6, 1, 4], dtype=int64)

In [1]:
import os

In [2]:
file_list = os.listdir('../data/total_data/')
file_list

['동별 데이터.xlsx',
 '부산상권정보.csv',
 '시간대별 승하차 인원 통합(2021_2022_08).csv',
 '역별 데이터.xlsx',
 '지하철 역사 내 상가 임대 정보.csv',
 '출퇴근시간 유동인구_2021.xlsx']

In [7]:
file_list[0]

'동별 데이터.xlsx'

In [12]:
import re 

print(re.search('xlsx',file_list[0]))

<re.Match object; span=(7, 11), match='xlsx'>
